pipeline {
    agent  any
      triggers {
        pollSCM "* * * * *"
       } 	
    stages {

      stage ('Checkout SCM'){
        steps {
          echo '=== Checking out code from Git ==='		
          git "url: 'https://github.com/Deepu206/terraform1.git"
        }
      }
      stage('Set Terraform path') {
       steps {
         script {
            def tfHome = tool name: 'terraform'
            env.PATH = "${tfHome}:${env.PATH}"
         }
     }
  }
     stage('terraform init') {
       when {
                branch 'main'
       } 	  
       steps {
           dir ("vpc") {
                script {
                    withAWS(roleAccount:'510417014637', role:'terraform-jenkin-role', useNode: true) {
                    sh 'terraform init -no-color'
                    }
             }
           }
        }
      }

   stage('terraform Plan') {
       when {
           branch 'main'
       } 	  
       steps {
           dir ("vpc") {
            
               script {
                    withAWS(roleAccount:'510417014637', role:'terraform-jenkin-role', useNode: true) {
                    sh 'terraform plan -no-color -out=plan.out'
                    }
               }
            }
        }
      }

  stage('Waiting for Approvals') {   
     when {
                branch 'main'
       }	      
      steps{
          input('Plan Validated? Please approve to create VPC Network in AWS?')
			  }
      }    

  stage('terraform Apply') {
 
       steps {
           dir ("vpc") {
            
              script {
                    withAWS(roleAccount:'510417014637', role:'terraform-jenkin-role', useNode: true) {
                    sh 'terraform apply -no-color -auto-approve plan.out'
                    sh "terraform output"
                    }
              }
            
           }
        }
      }
   }
}
